title: Yuexi Du
description: Medical Image Analysis & CV
site_title: '@XYPB - Yuexi Du'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: XYPB
blog_url: https://xypb.github.io/
email: yuexi.du@yale.edu
keybase_username: XYPB
twitter_username: yuexi_du
reddit_username: XYPB

# absolute or relative
profile_picture: assets/images/selfish_square.png

# Google Analytics ID
google_analytics: 